version: '2'
services:
  drupal:
    image: ittbcontainers/docker_drupal:stage
    volumes:
      - "/var/www:/var/www"
      - "/efs:/efs"
    restart: always
    ports:
      - "80:80"
      - "443:443"
