version: '2'
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
      - "/efs:/efs"
    restart: always
    ports:
    - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  redis:
    image: redis:3.0
    ports:
    - "6379"
    depends_on:
    - db
  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile
    volumes:
      - "/var/www:/var/www"
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    links:
      - db
      - redis
  varnish:
    build:
      context: ./varnish
      dockerfile: Dockerfile
    ports:
    - "80:6081"
    depends_on:
    - drupal
