version: '2'
services:
  db:
    image: seshagirisriram/docker_mysql_56
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
      - "/var/www:/var/www"
      - "/efs:/efs"
    restart: always
    ports:
    - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  drupal:
    image: seshagirisriram/docker_drupal:dev
    volumes:
      - "/var/www:/var/www"
      - "/efs:/efs"
    restart: always
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASS: drupal
      DRUPAL_DB_HOST: drupal
    links:
      - db
  varnish:
    image: seshagirisriram/docker_varnish
    ports:
    - "80:6081"
    depends_on:
    - drupal
