version: '2'
services:
  nagios:
    build:
      context: ./nagios 
      dockerfile: Dockerfile
    ports:
    - "80:80"
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    ports:
    - "8983:8983"
