version: '2'
services:
  db:
    image: seshagirisriram/docker_mysql
    command: ["mysqld", "--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
      - "/efs:/efs"
    restart: always
    ports:
    - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  redis:
    image: redis:3.0
    ports:
    - "6379"
    depends_on:
    - db
  drupal:
    image: seshagirisriram/docker_drupal
    volumes:
      - "/var/www:/var/www"
      - "/efs:/efs"
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_ROOT_PASSWORD: some_password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    links:
      - db
      - redis
  varnish:
    image: seshagirisriram/docker_varnish
    ports:
    - "80:6081"
    depends_on:
    - drupal
