version: '2'
services:
  varnish:
    build:
      context: ./varnish
      dockerfile: Dockerfile_stage
      args: 
        BACKEND_HOST: 172.17.0.3
        BACKEND_PORT: 80 
    ports:
    - "80:6081"
    volumes:
      - "/efs:/efs"
    restart: always
    environment:
      BACKENDS: "hostnameofdrupal"


    

